/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'siderust.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./siderust.android-arm64.node')
          } else {
            nativeBinding = require('@siderust/siderust-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'siderust.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./siderust.android-arm-eabi.node')
          } else {
            nativeBinding = require('@siderust/siderust-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'siderust.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./siderust.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@siderust/siderust-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'siderust.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./siderust.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@siderust/siderust-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'siderust.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./siderust.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@siderust/siderust-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'siderust.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./siderust.darwin-universal.node')
      } else {
        nativeBinding = require('@siderust/siderust-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'siderust.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./siderust.darwin-x64.node')
          } else {
            nativeBinding = require('@siderust/siderust-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'siderust.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./siderust.darwin-arm64.node')
          } else {
            nativeBinding = require('@siderust/siderust-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'siderust.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./siderust.freebsd-x64.node')
      } else {
        nativeBinding = require('@siderust/siderust-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'siderust.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./siderust.linux-x64-musl.node')
            } else {
              nativeBinding = require('@siderust/siderust-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'siderust.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./siderust.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@siderust/siderust-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'siderust.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./siderust.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@siderust/siderust-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'siderust.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./siderust.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@siderust/siderust-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'siderust.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./siderust.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@siderust/siderust-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'siderust.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./siderust.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@siderust/siderust-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'siderust.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./siderust.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@siderust/siderust-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'siderust.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./siderust.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@siderust/siderust-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'siderust.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./siderust.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@siderust/siderust-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { getPlanet, listBodies, transformDirection, directionToHorizontal, geodeticToEcef, angularSeparation, cartesianDistance, cartesianMagnitude, dotProduct, directionToCartesian, vsop87Heliocentric, vsop87Barycentric, vsop87SunBarycentric, vsop87EarthBarycentric, vsop87EarthHeliocentric, vsop87MoonGeocentric, transformPositionCenter, transformPositionFrame, orbitalPeriodDays, bodyAltitudeAt, bodyAzimuthAt, bodyCrossings, bodyCulminations, bodyAboveThreshold, bodyBelowThreshold, bodyAzimuthCrossings, bodyAzimuthExtrema, starAltitudeAt, starAzimuthAt, starCrossings, starCulminations, starAboveThreshold, starBelowThreshold, starAzimuthCrossings, starAzimuthExtrema, intersectPeriods, Observer, moonPhase, moonPhaseTopocentric, findPhaseEvents, moonIlluminationAbove, moonIlluminationBelow, moonIlluminationRange, Star, listCatalogStars, version } = nativeBinding

module.exports.getPlanet = getPlanet
module.exports.listBodies = listBodies
module.exports.transformDirection = transformDirection
module.exports.directionToHorizontal = directionToHorizontal
module.exports.geodeticToEcef = geodeticToEcef
module.exports.angularSeparation = angularSeparation
module.exports.cartesianDistance = cartesianDistance
module.exports.cartesianMagnitude = cartesianMagnitude
module.exports.dotProduct = dotProduct
module.exports.directionToCartesian = directionToCartesian
module.exports.vsop87Heliocentric = vsop87Heliocentric
module.exports.vsop87Barycentric = vsop87Barycentric
module.exports.vsop87SunBarycentric = vsop87SunBarycentric
module.exports.vsop87EarthBarycentric = vsop87EarthBarycentric
module.exports.vsop87EarthHeliocentric = vsop87EarthHeliocentric
module.exports.vsop87MoonGeocentric = vsop87MoonGeocentric
module.exports.transformPositionCenter = transformPositionCenter
module.exports.transformPositionFrame = transformPositionFrame
module.exports.orbitalPeriodDays = orbitalPeriodDays
module.exports.bodyAltitudeAt = bodyAltitudeAt
module.exports.bodyAzimuthAt = bodyAzimuthAt
module.exports.bodyCrossings = bodyCrossings
module.exports.bodyCulminations = bodyCulminations
module.exports.bodyAboveThreshold = bodyAboveThreshold
module.exports.bodyBelowThreshold = bodyBelowThreshold
module.exports.bodyAzimuthCrossings = bodyAzimuthCrossings
module.exports.bodyAzimuthExtrema = bodyAzimuthExtrema
module.exports.starAltitudeAt = starAltitudeAt
module.exports.starAzimuthAt = starAzimuthAt
module.exports.starCrossings = starCrossings
module.exports.starCulminations = starCulminations
module.exports.starAboveThreshold = starAboveThreshold
module.exports.starBelowThreshold = starBelowThreshold
module.exports.starAzimuthCrossings = starAzimuthCrossings
module.exports.starAzimuthExtrema = starAzimuthExtrema
module.exports.intersectPeriods = intersectPeriods
module.exports.Observer = Observer
module.exports.moonPhase = moonPhase
module.exports.moonPhaseTopocentric = moonPhaseTopocentric
module.exports.findPhaseEvents = findPhaseEvents
module.exports.moonIlluminationAbove = moonIlluminationAbove
module.exports.moonIlluminationBelow = moonIlluminationBelow
module.exports.moonIlluminationRange = moonIlluminationRange
module.exports.Star = Star
module.exports.listCatalogStars = listCatalogStars
module.exports.version = version
